// 이 파일은 `scripts/import-idioms.mjs`가 만듭니다 — 직접 고치지 마세요.
// 숙어를 추가·수정하려면 `scripts/idiom-source.xlsx`를 고치고 다시 실행하세요.
//
//   node scripts/import-idioms.mjs

/** 표제어는 기본형. 굴절형·소유격은 `idiomLookupKeys`가 되돌린다. */
export const IDIOM_MEANINGS: Record<string, string> = {
  // ── 동사+전치사 ──
  "agree with": "~에 동의하다",
  "arrive at": "~에 도착하다",
  "arrive in": "~에 도착하다",
  "ask for": "~을 요청하다",
  "belong to": "~에 속하다",
  "depend on": "~에 달려 있다",
  "laugh at": "~을 비웃다",
  "listen to": "~을 듣다",
  "look after": "~을 돌보다",
  "look at": "~을 보다",
  "look for": "~을 찾다",
  "look like": "~처럼 보이다, 닮다",
  "pay for": "~의 값을 지불하다",
  "prepare for": "~을 준비하다",
  "talk about": "~에 대해 이야기하다",
  "think of": "~을 생각하다",
  "wait for": "~을 기다리다",

  // ── 구동사 ──
  "break down": "고장 나다",
  "carry on": "계속하다",
  "check out": "확인하다, 살펴보다",
  "clean up": "청소하다, 정리하다",
  "come across": "우연히 마주치다",
  "come back": "돌아오다",
  "figure out": "이해하다, 알아내다",
  "find out": "알아내다",
  "get off": "내리다",
  "get on": "타다",
  "get up": "일어나다",
  "give back": "돌려주다",
  "give up": "포기하다",
  "go back": "돌아가다",
  "go on": "계속하다",
  "go out": "외출하다",
  "grow up": "성장하다",
  "hand in": "제출하다",
  "hand out": "나눠주다",
  "hurry up": "서두르다",
  "look up": "찾아보다",
  "pick up": "집다 / 데리러 가다",
  "point out": "지적하다",
  "put away": "치우다",
  "put off": "미루다",
  "put on": "입다, 착용하다",
  "run away": "도망가다",
  "set up": "설치하다, 세우다",
  "show up": "나타나다",
  "sit down": "앉다",
  "stand up": "일어서다",
  "take off": "벗다 / 이륙하다",
  "take out": "꺼내다",
  "throw away": "버리다",
  "try on": "입어 보다",
  "turn off": "끄다",
  "turn on": "켜다",
  "wake up": "잠에서 깨다",
  "write down": "적다",

  // ── 숙어 ──
  "a lot of": "많은",
  "above all": "무엇보다도",
  "according to": "~에 따르면",
  "across from": "~ 맞은편에",
  "after all": "결국, 어쨌든",
  "again and again": "몇 번이고",
  "all of a sudden": "갑자기",
  "all over": "곳곳에",
  "all the time": "항상",
  "and so on": "기타 등등",
  "as a result": "결과적으로",
  "as if": "마치 ~처럼",
  "as long as": "~하는 한",
  "as much as": "~만큼",
  "as soon as": "~하자마자",
  "as usual": "평소처럼",
  "as well as": "~뿐만 아니라",
  "at all": "전혀",
  "at first": "처음에는",
  "at last": "마침내",
  "at least": "적어도",
  "at once": "즉시",
  "at the same time": "동시에",
  "be about to": "막 ~하려고 하다",
  "be afraid of": "~을 두려워하다",
  "be angry with": "~에게 화가 나다",
  "be bad at": "~을 못하다",
  "be based on": "~에 근거하다",
  "be busy with": "~로 바쁘다",
  "be covered with": "~로 덮여 있다",
  "be different from": "~와 다르다",
  "be excited about": "~에 신이 나다",
  "be famous for": "~로 유명하다",
  "be filled with": "~로 가득 차다",
  "be full of": "~로 가득하다",
  "be going to": "~할 것이다",
  "be good at": "~을 잘하다",
  "be interested in": "~에 관심이 있다",
  "be kind to": "~에게 친절하다",
  "be known for": "~로 알려지다",
  "be late for": "~에 늦다",
  "be made from": "~로 만들어지다",
  "be made of": "~로 만들어지다",
  "be proud of": "~을 자랑스러워하다",
  "be ready for": "~할 준비가 되다",
  "be ready to": "~할 준비가 되다",
  "be related to": "~와 관련이 있다",
  "be similar to": "~와 비슷하다",
  "be sorry for": "~을 미안해하다",
  "be surprised at": "~에 놀라다",
  "be tired of": "~에 싫증나다",
  "be used to": "~에 익숙하다",
  "be worried about": "~을 걱정하다",
  "because of": "~ 때문에",
  "bring back": "돌려주다",
  "bring up": "기르다 / 꺼내다",
  "by oneself": "혼자서",
  "by the way": "그런데",
  "call back": "다시 전화하다",
  "call off": "취소하다",
  "care about": "~에 관심을 갖다",
  "care for": "~을 돌보다",
  "carry out": "수행하다",
  "change one's mind": "마음을 바꾸다",
  "check in": "체크인하다",
  "close to": "~에 가까이",
  "come along": "함께 가다",
  "come in": "들어오다",
  "come out": "나오다",
  "come true": "실현되다",
  "cut down": "베다 / 줄이다",
  "cut off": "잘라 내다",
  "deal with": "~을 다루다, 처리하다",
  "do one's best": "최선을 다하다",
  "each other": "서로",
  "enjoy oneself": "즐겁게 보내다",
  "even if": "비록 ~일지라도",
  "even though": "비록 ~이지만",
  "far from": "~에서 멀리",
  "fill in": "채워 넣다",
  "fill out": "작성하다",
  "first of all": "우선",
  "for a while": "잠시 동안",
  "for example": "예를 들어",
  "for the first time": "처음으로",
  "from now on": "지금부터",
  "from time to time": "때때로",
  "get along": "잘 지내다",
  "get along with": "~와 잘 지내다",
  "get back": "돌아오다",
  "get rid of": "~을 없애다",
  "get together": "모이다",
  "get well": "회복하다",
  "give away": "나눠 주다",
  "go away": "가 버리다",
  "go through": "~을 겪다",
  "had better": "~하는 것이 좋다",
  "hang out": "어울려 놀다",
  "hang up": "전화를 끊다",
  "have a good time": "즐거운 시간을 보내다",
  "hear from": "~에게서 소식을 듣다",
  "help oneself": "마음껏 먹다",
  "in a hurry": "서둘러",
  "in addition": "게다가",
  "in common": "공통으로",
  "in danger": "위험에 처한",
  "in fact": "사실은",
  "in front of": "~ 앞에",
  "in general": "일반적으로",
  "in one's opinion": "~의 생각으로는",
  "in order to": "~하기 위해",
  "in other words": "다시 말해서",
  "in particular": "특히",
  "in spite of": "~에도 불구하고",
  "in the end": "결국",
  "in the future": "미래에",
  "in the past": "과거에",
  "in time": "시간에 맞게",
  "in trouble": "곤경에 처한",
  "instead of": "~ 대신에",
  "keep in touch": "계속 연락하다",
  "keep on": "계속하다",
  "keep one's word": "약속을 지키다",
  "leave for": "~을 향해 떠나다",
  "little by little": "조금씩",
  "look around": "둘러보다",
  "look forward to": "~을 기대하다",
  "look into": "~을 조사하다",
  "lose one's temper": "화를 내다",
  "lose one's way": "길을 잃다",
  "make friends with": "~와 친구가 되다",
  "make oneself at home": "편히 쉬다",
  "make sure": "확실히 하다",
  "make up": "지어내다 / 화해하다",
  "make up one's mind": "결심하다",
  "more and more": "점점 더 많은",
  "move on": "넘어가다",
  "next to": "~ 옆에",
  "no longer": "더 이상 ~않다",
  "no matter what": "무엇이든 상관없이",
  "no one": "아무도 ~않다",
  "not at all": "전혀 ~아니다",
  "not only": "~뿐만 아니라",
  "of course": "물론",
  "on one's way": "~로 가는 길에",
  "on the other hand": "반면에",
  "on the way to": "~로 가는 길에",
  "on time": "정시에",
  "once again": "다시 한번",
  "one another": "서로",
  "one by one": "하나씩",
  "out of": "~밖으로",
  "over and over": "반복해서",
  "over here": "여기에",
  "over there": "저기에",
  "put down": "내려놓다",
  "put up": "세우다 / 붙이다",
  "put up with": "~을 참다",
  "right away": "즉시",
  "right now": "지금 당장",
  "run into": "우연히 만나다",
  "side by side": "나란히",
  "so far": "지금까지",
  "stand for": "~을 상징하다",
  "step by step": "한 단계씩",
  "such as": "~와 같은",
  "take a look at": "~을 살펴보다",
  "take away": "가져가다",
  "take care of": "~을 돌보다",
  "take one's time": "천천히 하다",
  "take part in": "~에 참가하다",
  "take place": "일어나다, 개최되다",
  "take turns": "번갈아 하다",
  "talk to": "~에게 말을 걸다",
  "talk with": "~와 이야기하다",
  "thank you for": "~에 대해 고맙다",
  "thanks to": "~ 덕분에",
  "the same as": "~와 같은",
  "these days": "요즘",
  "think about": "~에 대해 생각하다",
  "try out": "시험해 보다",
  "turn around": "돌아서다",
  "turn down": "거절하다 / 소리를 줄이다",
  "turn into": "~로 변하다",
  "turn up": "나타나다 / 소리를 높이다",
  "used to": "~하곤 했다",
  "work on": "~에 공들이다",
  "work out": "운동하다 / 잘 풀리다",
  "worry about": "~을 걱정하다",

  // ── 표현 ──
  "a few": "몇몇의, 약간의",
  "a little": "약간의",
  "a pair of": "한 쌍의",
  "be able to": "~할 수 있다",
  "catch a cold": "감기에 걸리다",
  "come from": "~ 출신이다",
  "go to bed": "잠자리에 들다",
  "have to": "~해야 한다",
  "how about": "~은 어때?",
  "how to": "~하는 방법",
  "keep a promise": "약속을 지키다",
  "less than": "~보다 적은",
  "make a mistake": "실수하다",
  "more than": "~보다 많은",
  "most of": "~의 대부분",
  "one of": "~ 중 하나",
  "so that": "~하도록",
  "take a break": "휴식을 취하다",
  "take a picture": "사진을 찍다",
  "take a walk": "산책하다",
  "would like to": "~하고 싶다",

  // ── 구문 ──
  "enough to": "~할 만큼 충분히",

};

/**
 * `too ... to` 처럼 빈칸이 있는 구문 패턴.
 * 표면형이 그대로 나타나지 않아 `lookupIdiomMeaning`으로는 찾을 수 없다 —
 * 구문 학습 기능을 붙일 때 쓰려고 원본 그대로 남겨 둔다.
 */
export const IDIOM_PATTERNS: Record<string, string> = {
  "cannot help -ing": "~하지 않을 수 없다",
  "feel like -ing": "~하고 싶다",
  "be busy -ing": "~하느라 바쁘다",
  "be worth -ing": "~할 가치가 있다",
  "too ... to": "너무 ~해서 …할 수 없다",
  "not only ... but also": "~뿐만 아니라 …도",
  "either A or B": "A 또는 B",
  "neither A nor B": "A도 B도 아닌",
  "both A and B": "A와 B 둘 다",
  "not ... at all": "전혀 ~않다",
  "as ... as possible": "가능한 한 ~하게",
};
